name: "Discord"

on:
  workflow_dispatch:  
    inputs:  
      skip_post:
        description: 'Skip posting to Social Media'
        required: false
        type: boolean  
  schedule:
    # - cron: "0 */1 * * *" # every 1 hour
    - cron: "*/30 * * * *" # every 30 minutes
    # - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Download Cache
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: metadata
      #     path: metadata
      - name: Check Cache
        run: |
          cat metadata || echo "No cache found"
      - name: Package Installer
        run: |
          sudo snap install ipsw
      - name: Run ipsw watch WebKit/WebKit
        run: |
          /snap/bin/ipsw watch WebKit/WebKit --pattern '(?i)Lockdown Mode' --days 1 --cache metadata \
          --api ${{ secrets.GITHUB_TOKEN }} \
          --discord \
          --discord-id ${{ secrets.DISCORD_ID }} \
          --discord-token ${{ secrets.DISCORD_TOKEN }} \
          --discord-icon "https://raw.githubusercontent.com/blacktop/ipsw/master/www/static/img/webkit.png"
      - name: Run ipsw watch apple-oss-distributions/distribution-macOS
        if: ${{ !inputs.skip_post }}
        run: |
          /snap/bin/ipsw watch apple-oss-distributions/distribution-macOS --tags --post --cache metadata \
          --api ${{ secrets.GITHUB_TOKEN }} \
          --discord \
          --discord-id ${{ secrets.DISCORD_ID }} \
          --discord-token ${{ secrets.DISCORD_TOKEN }} \
          --discord-icon "https://avatars.githubusercontent.com/u/91919287"
        # --mastodon \
        # --mastodon-client-id ${{ secrets.MASTODON_CLIENT_ID }} \
        # --mastodon-client-secret ${{ secrets.MASTODON_CLIENT_SECRET }} \
        # --mastodon-access-token ${{ secrets.MASTODON_ACCESS_TOKEN }}
      - name: Run ipsw watch apple-oss-distributions/distribution-macOS (SKIP MASTODON)
        if: ${{ inputs.skip_post }}
        run: |
          /snap/bin/ipsw watch apple-oss-distributions/distribution-macOS --tags --post --cache metadata \
          --api ${{ secrets.GITHUB_TOKEN }} \
          --discord \
          --discord-id ${{ secrets.DISCORD_ID }} \
          --discord-token ${{ secrets.DISCORD_TOKEN }} \
          --discord-icon "https://avatars.githubusercontent.com/u/91919287"
        # --mastodon \
        # --mastodon-client-id ${{ secrets.MASTODON_CLIENT_ID }} \
        # --mastodon-client-secret ${{ secrets.MASTODON_CLIENT_SECRET }} \
        # --mastodon-access-token ${{ secrets.MASTODON_ACCESS_TOKEN }}
      - name: Upload metadata
        uses: actions/upload-artifact@v4
        with:
          name: metadata
          path: metadata
          overwrite: true
          retention-days: 90